create database constrant;
use constrant;
select database();
create table if not exists test1 (id int,age int);
insert into test1 values(101,20),(102,null);
select * from test1;
create table if not exists test2 (id int,age int not null);
insert into test2 values(101,20),(102,null);
select * from test2;
create table if not exists test3 (id int unique,age int);
insert into test3 values(101,20),(101,30);
select * from test3;
create table if not exists test5 (id int default 100,age int);
insert into test5(age) values(20),(null);
select * from test5;
create table if not exists test6(id int ,age int);
insert into test6(age) values(20),(null);
select * from test6;
create table if not exists test7 (id int ,age int check (age>18));
insert into test7 values (1,50);
insert into test7 values (1,10);
select * from test7;
create table if not exists test9 (id int ,age int check (age between 18 and 22));
insert into test9 values (1,50);
insert into test9 values (1,19);
create table student(id int ,name varchar(20),cname varchar(20));
insert into student values(1,'naina',10),(2,'abhi',12);
create table class(cname varchar(20) primary key);
insert into class values(10),(8),(9);
select * from class;
drop table student;
create table student(id int ,name varchar(20),cname varchar(20),  foreign  key(cname) references class(cname));
insert into student values(1,'naina',8),(2,'abhi',9);
select * from student;